stages:
- build

create_image:
  stage: build
  only:
  - master
  - tags
  - web

  image: docker:stable
  variables:
    DCR_REGISTRY: registry.crplab.ru
    DCR_IMAGE_NAME: buldozer/services
    DCR_IMAGE_TAG: latest
    TAGRELEASE_URL: https://github.com/dikderoy/tagrelease/releases/download/v1.1.0/tagrelease-linux-amd64

  cache:
    paths:
    - tagrelease

  before_script:
  - docker info
  - apk add --no-cache git
  - if [ ! -f tagrelease ]; then wget -O tagrelease $TAGRELEASE_URL && chmod +x tagrelease; fi
  script:
  - DCR_IMAGE_VTAG=`./tagrelease -i patch -e -`
  - DCR_FIN="$DCR_REGISTRY/$DCR_IMAGE_NAME:$DCR_IMAGE_TAG"
  - DCR_VFIN="$DCR_REGISTRY/$DCR_IMAGE_NAME:$DCR_IMAGE_VTAG"
  - echo $DCR_VFIN

  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DCR_REGISTRY
  - docker build -t $DCR_FIN --build-arg PLATFORM_VERSION=$(./tagrelease) -f docker/Unsupervised.Dockerfile .
  - docker tag $DCR_FIN $DCR_VFIN
  - docker push $DCR_FIN
  - docker push $DCR_VFIN
