stages:
- build

create_image:
  stage: build
  only:
  - master
  - tags
  - web

  image: docker:stable
  variables:
    DCR_IMAGE_NAME: git.crplab.ru:5050/buldozer/services
    DCR_IMAGE_TAG: latest
    TAGRELEASE_URL: https://github.com/dikderoy/tagrelease/releases/download/v1.1.0/tagrelease-linux-amd64

  cache:
    paths:
    - tagrelease

  before_script:
  - docker info
  - apk add --no-cache git
  - ls -lah .
  - if [ ! -f tagrelease ]; then wget -O tagrelease $TAGRELEASE_URL && chmod +x tagrelease; fi
  script:
  - DCR_IMAGE_VTAG=`./tagrelease -i patch -e -`
  - echo $DCR_IMAGE_VTAG
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.crplab.ru:5050
  - docker build -t $DCR_IMAGE_NAME:$DCR_IMAGE_TAG -f docker/Unsupervised.Dockerfile .
  - docker tag $DCR_IMAGE_NAME:$DCR_IMAGE_TAG $DCR_IMAGE_NAME:$DCR_IMAGE_VTAG
  - docker push $DCR_IMAGE_NAME:$DCR_IMAGE_TAG
  - docker push $DCR_IMAGE_NAME:$DCR_IMAGE_VTAG
