version: '2'
services:
  app_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: applications
    env_file:
      - dsn.env
    ports:
      - '8080:8080'

  mongo:
    image: mongo:3.6
    volumes:
      - ./docker/mongodb-data:/data/db


#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./docker/tyk.nginx:/etc/nginx/conf.d/tyk.conf

