---
version: '2'
services:
  app_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=applications
    env_file:
    - dsn.env
    volumes:
    - ./docker/app-data:/opt/data

  model_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=models
    env_file:
    - dsn.env
    volumes:
    - ./docker/app-data:/opt/data

  env_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=envmanager
    env_file:
    - dsn.env

  wsp_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=workspaces
    env_file:
    - dsn.env

  mongo:
    image: mongo:3.6
    volumes:
    - ./docker/mongodb-data:/data/db


  nginx:
    image: nginx:latest
    volumes:
    - ./docker/local.nginx:/etc/nginx/conf.d/default.conf

  consul:
    image: consul:1.2.2
    command: agent -dev -bootstrap -ui -bind=0.0.0.0 -client=0.0.0.0
    ports:
    - '8500:8500'
