---
version: '2'
services:
  app_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: applications
    env_file:
    - dsn.env
    volumes:
    - ./docker/app-data:/opt/data

  model_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: models
    env_file:
    - dsn.env
    volumes:
    - ./docker/app-data:/opt/data

  env_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: envmanager
    env_file:
    - dsn.env

  wsp_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: workspaces
    env_file:
    - dsn.env

  mongo:
    image: mongo:3.6
    volumes:
    - ./docker/mongodb-data:/data/db


  nginx:
    image: nginx:latest
    volumes:
      - ./docker/local.nginx:/etc/nginx/conf.d/default.conf

