---
version: '3.7'
services:
  app_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=applications
    env_file:
    - dsn.env
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  model_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=models
    env_file:
    - dsn.env
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  env_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=envmanager
    - TRAEFIK_ENABLE=false
    env_file:
    - dsn.env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  wsp_manager:
    build:
      dockerfile: docker/Dockerfile
      context: .
    environment:
    - SERVICE_NAME=workspaces
    env_file:
    - dsn.env
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  mongo:
    image: mongo:3.6
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  consul:
    image: consul:1.2.2
    command: agent -dev -bootstrap -ui -client=0.0.0.0
    environment:
    - CONSUL_BIND_INTERFACE=eth0
    ports:
    - '8500:8500'
    networks:
    - default
    - buldozer_usp_net
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  traefik:
    image: traefik:1.6
    volumes:
    - ./docker/traefik.toml:/traefik.toml
    ports:
    - '80:80'
    - '8080:8080'
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  zookeeper:
    image: zookeeper:3.4
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
    - KAFKA_BROKER_ID=1

    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    - KAFKA_CREATE_TOPICS=correlations:5:1,events:5:1
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_DELETE_TOPIC_ENABLE=true

    - KAFKA_LOG_RETENTION_BYTES=200000000
    - KAFKA_LOG_SEGMENT_BYTES=20000000
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'

  subordinate:
    build:
      context: .
      dockerfile: docker/Subordinate.Dockerfile

networks:
  default:
  buldozer_usp_net:
    name: buldozer_usp_net
